# Generated by Django 5.0.2 on 2024-12-26 16:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_created_at_document_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
